### ISSUE TITLE
What are the accredited papers to achieve these models?

### ISSUE THREAD

**Issue by mohamd34** [tsaglam/TrafficSimulation#1]
Any links for the sources (papers, links,....etc), that you used to achieve these models please?

**Comment by pskopnik** [comment]
This project is course work for a parallel programming course at KIT. It implements a model described in the task assignment which is not public and we unfortunately cannot share outside of the university's network. However, the basis is the MOBIL model for which publications exist. The most cited seems to be [Kresting e.a.: General Lane-Changing Model MOBIL for Car-Following Models](https://journals.sagepub.com/doi/abs/10.3141/1999-10).

**Comment by tsaglam** [comment]
If I remember correctly, this project is also based on the [Intelligent Driver Model (IDM)](https://en.wikipedia.org/wiki/Intelligent_driver_model) by [Treiber et al](https://journals.aps.org/pre/abstract/10.1103/PhysRevE.62.1805). However, the original IDM is a single-lane model, which is extended to a multi-lane model to facilitate the use of the previously mentioned MOBIL model.
